Traceback (most recent call last):
  File "/home/pi/smartmirror/smartmirror.py", line 7, in <module>
    from calendar_display import get_combined_events
  File "/home/pi/smartmirror/calendar_display.py", line 9, in <module>
    from google.oauth2.credentials import Credentials
ModuleNotFoundError: No module named 'google'
Traceback (most recent call last):
  File "/home/pi/smartmirror/smartmirror.py", line 7, in <module>
    from calendar_display import get_combined_events
  File "/home/pi/smartmirror/calendar_display.py", line 9, in <module>
    from google.oauth2.credentials import Credentials
ModuleNotFoundError: No module named 'google'
Traceback (most recent call last):
  File "/home/pi/smartmirror/smartmirror.py", line 7, in <module>
    from calendar_display import get_combined_events
  File "/home/pi/smartmirror/calendar_display.py", line 9, in <module>
    from google.oauth2.credentials import Credentials
ModuleNotFoundError: No module named 'google'
Traceback (most recent call last):
  File "/home/pi/smartmirror/smartmirror.py", line 7, in <module>
    from calendar_display import get_combined_events
  File "/home/pi/smartmirror/calendar_display.py", line 9, in <module>
    from google.oauth2.credentials import Credentials
ModuleNotFoundError: No module named 'google'
Traceback (most recent call last):
  File "/home/pi/smartmirror/smartmirror.py", line 7, in <module>
    from calendar_display import get_combined_events
  File "/home/pi/smartmirror/calendar_display.py", line 9, in <module>
    from google.oauth2.credentials import Credentials
ModuleNotFoundError: No module named 'google'
Traceback (most recent call last):
  File "/home/pi/smartmirror/smartmirror.py", line 7, in <module>
    from calendar_display import get_combined_events
  File "/home/pi/smartmirror/calendar_display.py", line 9, in <module>
    from google.oauth2.credentials import Credentials
ModuleNotFoundError: No module named 'google'
